### ISSUE TITLE
Large `mem::size_of` for `EliasFano`

### ISSUE THREAD

**Issue by sujayakar** [kampersanda/sucds#96]
I ran into a stack overflow in my system since `EliasFano` takes up 336 bytes on the stack! The main culprit is `DArray`, which takes up 288 bytes. It looks like the main issue is structures like `DArrayIndex`, which include three different heap allocations, which each take 24 bytes. Then, `DArray` has two `DArrayIndex`es and a `Rank9SelIndex`.

I'm just `Box`ing these structures in my system for now, but I'm curious if you'd be interested in PRs to make the structures more space efficient. Here are some ideas:
- Change `Vec<T>` to `Box<[T]>` for immutable structures. This takes the per-allocation cost down from 24 to 16 bytes.
- Merge allocations in top-level structures like `EliasFano` into a single, large heap allocation. This will likely make the code uglier but (1) have better heap utilization, since we can make a single, precise allocation, and (2) dramatically reduce stack usage.

**Comment by kampersanda** [comment]
Thank you for your report and suggestions!

> I'm curious if you'd be interested in PRs to make the structures more space efficient.

It is no at this point. I would guess that such a problem occurs on limited systems and is not critical in general. For example, the default stack size on all Tier-1 platforms seems to be 2 MiB ([Ref](https://doc.rust-lang.org/std/thread/#stack-size)).

Now, I would like to focus on organizing modules and adding new implementations, rather than supporting more limited systems. However, when we get to the development stage of exploring more memory-saving implementations, your ideas will be very interesting.

**Comment by sujayakar** [comment]
Sounds good! I'll let you know if I make any of these optimizations in a fork, but I suspect `Box<EliasFano>` will be good enough for now. It makes sense to me to focus on adding new implementations for now.
